FROM python:3.12-slim-bullseye
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

# Best practice to pin to a specific version of uv
COPY --from=ghcr.io/astral-sh/uv:0.3.0 /uv /bin/uv

ARG UID
ARG GID
ARG GROUPNAME
RUN echo exit 0 > /usr/sbin/policy-rc.d

RUN apt-get update && apt install -y sudo && \
    groupadd -g $GID $GROUPNAME && \
    useradd -m -u $UID -g $GID devuser && \
    echo devuser:devuser | chpasswd && \
    usermod -aG sudo devuser

USER devuser
WORKDIR /home/devuser/tsp-opt

# These are for productino settings
# RUN uv sync
ENV VIRTUAL_ENV=/home/devuser/.venv
ENV PATH="/home/devuser/.venv/bin:$PATH"
# COPY --chown=${UID}:${GID} pyproject.toml ./
# RUN uv pip install -r pyproject.toml
# RUN uv pip install -e .

CMD ["uv", "pip", "install", "pyproject.toml"]
